#!/usr/bin/env bash
export BASEDIR=$(pwd)
export MAKEOBJDIRPREFIX=$BASEDIR/obj
cd $BASEDIR/src
if [ -n "$1" ]; then
  DST="$1"
else
  DST="$BASEDIR/nfsroot/tree"
fi
sudo -E make installkernel TARGET_ARCH=aarch64 KERNCONF=IMX DESTDIR=$DST -j6
